AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Jenkins EC2 instance'

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: String
  PublicKeyMaterial:
    Description: The public key material
    Type: String

Resources:
  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and Jenkins port
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  JenkinsKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref KeyName
      PublicKeyMaterial: !Ref PublicKeyMaterial

  JenkinsInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      SecurityGroups:
        - !Ref JenkinsSecurityGroup
      KeyName: !Ref KeyName
      ImageId: ami-0261755bbcb8c4a84  # Ubuntu 20.04 LTS
      Tags:
        - Key: Name
          Value: JenkinsServer

Outputs:
  EC2PublicIP:
    Description: Public IP address of the Jenkins instance
    Value: !GetAtt JenkinsInstance.PublicIp