name: Delete AWS Resources

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Get EC2 Public IP
      id: ec2-ip
      run: |
        EC2_IP=$(aws cloudformation describe-stacks --stack-name jenkins-ec2-stack --query "Stacks[0].Outputs[?OutputKey=='EC2PublicIP'].OutputValue" --output text)
        echo "ec2_ip=$EC2_IP" >> $GITHUB_OUTPUT

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > jenkins.pem
        chmod 600 jenkins.pem

    - name: Delete EKS Cluster
      run: |
        ssh -i jenkins.pem -o StrictHostKeyChecking=no ubuntu@${{ steps.ec2-ip.outputs.ec2_ip }} 'eksctl delete cluster --name mi-cluster-eks --region us-east-1'

    - name: Delete CloudFormation Stack
      run: |
        aws cloudformation delete-stack --stack-name jenkins-ec2-stack

    - name: Wait for CloudFormation Stack Deletion
      run: |
        aws cloudformation wait stack-delete-complete --stack-name jenkins-ec2-stack

    - name: Clean up EBS volumes
      run: |
        VOLUMES=$(aws ec2 describe-volumes --filters Name=status,Values=available --query "Volumes[*].VolumeId" --output text)
        for VOLUME in $VOLUMES; do
          aws ec2 delete-volume --volume-id $VOLUME
        done

    - name: Clean up Elastic IPs
      run: |
        EIPS=$(aws ec2 describe-addresses --query "Addresses[?AssociationId==null].AllocationId" --output text)
        for EIP in $EIPS; do
          aws ec2 release-address --allocation-id $EIP
        done