name: Cleanup EKS Cluster and CloudFormation Stack

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1  
  CLUSTER_NAME: cluster-PIN  

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Delete EKS Cluster
        run: |
          eksctl delete cluster --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Delete CloudFormation Stack
        run: |
          aws cloudformation delete-stack --stack-name jenkins-ec2-stack --region ${{ env.AWS_REGION }}

      - name: Wait for CloudFormation Stack to be deleted
        run: |
          aws cloudformation wait stack-delete-complete --stack-name jenkins-ec2-stack --region ${{ env.AWS_REGION }}
